# Cloudflare Pages configuration
name = "net-traffic"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[env.production]
name = "net-traffic"

[env.preview]
name = "net-traffic-preview"

